# Only for dev use
services:
  db:
    image: mariadb:10.11
    volumes:
      - mysql:/var/lib/mysql

      # Set up UTF8MB4 in config file for the container.
      # Needs to be done BEFORE the database is created.
      # *** Some other MariaDB settings were modified in the sample file:
      #        wait_timeout,  interactive_timeout, max_connections, net_read_timeout
      #        + skip-name-resolve
      # Note: It seems different versions of the MariaDB container need
      #       this file in different locations. Put in in both places.
      - './docker-config/db/mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf'
      - './docker-config/db/mariadb.cnf:/etc/mysql/mariadb.cnf'

      # Tuning MariaDB config - sample file
      # The sample file modifies wait_timeout, and adds skip-name-resolve
      #- "./docker-config/db/my.cnf:/etc/mysql/my.cnf"

      # Adjust open file limits for MariaDB/mySQL - sample file
      #- "./docker-config/db/limits.conf:/etc/security/limits.conf"

      # Provides read only access to the host system's /etc/localtime - tested on Linux hosts
      #- "/etc/localtime:/etc/localtime:ro"

      # The ulimits lines were only tested on Linux hosts in conjuction woth the limits.conf file
      #ulimits:
      #  nofile:
      #    soft: 4096
      #    hard: 4096

    restart: unless-stopped
    environment:
      # When the MariaDB container is first started it will set the
      # the MYSQL_ROOT_PASSWORD if there is no mysql database in the
      # data volume.
      MYSQL_ROOT_PASSWORD: ${WEBWORK_MYSQL_ROOT_PASSWORD}

      # When the MariaDB container is first started it will create
      #    the WW database and WW DB user based on:
      MYSQL_DATABASE: webwork
      MYSQL_USER: ${WEBWORK_DB_USER}
      MYSQL_PASSWORD: ${WEBWORK_DB_PASSWORD}

      # A timezone for the DB server can be set:
      #TZ: zone/city
      # where zone/city must be a valid setting.
      # "/usr/bin/timedatectl list-timezones" on an Ubuntu system with
      # that tool installed will find valid values.
      # See: https://stackoverflow.com/questions/39172652/using-docker-compose-to-set-containers-timezones
 
      # Enable the auto db upgrader when moving to a newer MariaDB version
      MARIADB_AUTO_UPGRADE: 1

  # dev frontend for db
  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8070:8080
    depends_on:
      - db

  app: &app
    # Set up the "build:" configuration:
    build:
      # For use/building when docker-compose.yml is in the webwork2 directory
      context: .
      # ubc custom dockerfile
      dockerfile: Dockerfile-prod

    depends_on:
      - db
      - r

    volumes:
      # ======================================================================

      # If you are using locally modified webwork2 files, then
      # either mount them from the webwork2 tree from which you start Docker:
      #- ".:/opt/webwork/webwork2"
      # OR mount it from a fixed external location
      #- "/path_to/webwork2:/opt/webwork/webwork2"

      # Shared main /pg repository - allows local PG development
      #- "/path_to_shared/pg:/opt/webwork/pg"
      # OR locally modified PG directory
      #- "../pg:/opt/webwork/pg"

      # ======================================================================

      # Sometimes it is helpful to mount certain webwork2/conf files from elsewhere
      # so the main contents of webwork2 can be shared by several hosts (ex. NFS)
      #- "/per_host_conf_path/conf/authen_LTI.conf:/opt/webwork/webwork2/conf/authen_LTI.conf"
      #- "/per_host_conf_path/conf/localOverrides.conf:/opt/webwork/webwork2/conf/localOverrides.conf"
      #- "/per_host_conf_path/conf/site.conf:/opt/webwork/webwork2/conf/site.conf"

      # webwork2 misc LOCAL files - mount live (per host) so NOT in the main webwork2 location
      #- "/per_host_conf_path/htdocs/my_site_info.txt:/opt/webwork/webwork2/htdocs/my_site_info.txt"

      # webwork2 LOCAL logs and htdocs/tmp directories (per host)
      #- "/per_host_data_path/webwork2/logs:/opt/webwork/webwork2/logs"
      #- "/per_host_data_path/webwork2/htdocs/tmp:/opt/webwork/webwork2/htdocs/tmp"

      # By default mount the courses tree in a separate tree outside of webwork2/ as follows:
      - '${COURSES_DIRECTORY_ON_HOST}:/opt/webwork/courses'
      # OR use the following mount if the hosts have different courses on them:
      #- "/per_host_data_path/courses/:/opt/webwork/courses/"

      # ======================================================================

      # Mojolicious webwork2 app configuration.  For production you will need to modify this file.
      # Note that the SSL configuration is done in this file.
      # See https://docs.mojolicious.org/Mojo/Server/Daemon#listen for how to do this.
      #- "/per_host_conf_path/conf/webwork2.mojolicious.yml:/opt/webwork/webwork2/conf/webwork2.mojolicious.yml"

      # SSL certificates (subdirectory with certificate and key)
      # Place your ssl certificate files used in webwork2.mojolicious.yml above in docker-config/ssl,
      # or change the mount location to where your ssl certificate files reside.
      #- "./docker-config/ssl/:/etc/ssl/local"

      # ======================================================================

      # By default the OPL is stored in a named Docker storage volume:
      - oplVolume:/opt/webwork/libraries/webwork-open-problem-library
      #
      # as an alternative, you can comment out the prior option and uncomment the line below to use
      # a local directory containing the OPL
      #- "/path_to/webwork-open-problem-library:/opt/webwork/libraries/webwork-open-problem-library"

      # ======================================================================

      # The app image keeps running OPL update if we don't store the resulting
      # taxonomy in a named volume
      - webworkHtdocsData:/opt/webwork/webwork2/htdocs/DATA

    hostname: myhost.mydomain.edu

    ports:
      # For a personal machine
      - '${WEBWORK2_HTTP_PORT_ON_HOST}:8080'

      # For a production machine
      #- "80:8080"
      #- "443:8080"

    # For a production machine
    #restart: always
    stop_grace_period: 5s

    environment:
      # Standard database environment variables needed by WeBWorK:
      WEBWORK_SECRET: 'veryverysecret'

      # Select which DBD driver to use
      WEBWORK_DB_DRIVER: MariaDB
      # WEBWORK_DB_DRIVER: mysql

      WEBWORK_DB_HOST: db
      WEBWORK_DB_PORT: 3306
      WEBWORK_DB_NAME: webwork

      # These are set in the .env file and import values from there
      WEBWORK_DB_PASSWORD: ${WEBWORK_DB_PASSWORD}
      WEBWORK_DB_USER: ${WEBWORK_DB_USER}

      # error pages will tell users to email this for support
      WEBWORK_SUPPORT_EMAIL: support@example.edu

      # =======================================================
      # Local configuration variables:

      # To turn on SSL in the running container
      #SSL: 1

      # Control settings for error message handling by webwork2/lib/WeBWorK.pm
      # The standard behavior is with both of these set to 0
      MIN_HTML_ERRORS: 0
      JSON_ERROR_LOG: 0

      # Change to A4 paper
      #PAPERSIZE: a4

      # Use to build additional locales in the running container at startup. Ex:
      #ADD_LOCALES: "he_IL ISO-8859-8\nhe_IL.UTF-8 UTF-8\n"

      # Extra Ubuntu packages to install during startup
      # Commenting the following line out will speed up container startup time.
      #ADD_APT_PACKAGES: nano less

      # The system timezone for the container can be set using
      #SYSTEM_TIMEZONE: zone/city
      # where zone/city must be a valid setting.
      # "/usr/bin/timedatectl list-timezones" on an Ubuntu system with
      # that tool installed will find valid values.

      # don't upload OPL stats to MAA servers
      SKIP_UPLOAD_OPL_statistic: 1

      # =======================================================

      # If you use https below, make sure to set up the certificate and SSL configuration
      # Note if your server uses a non-standard port, that should also be included.
      #WEBWORK_ROOT_URL: https://myhost.mydomain.edu
      WEBWORK_ROOT_URL: "http://localhost:${WEBWORK2_HTTP_PORT_ON_HOST}"

      WEBWORK_SMTP_SERVER: maildev
      WEBWORK_SMTP_PORT: 1025
      WEBWORK_SMTP_SENDER: no-reply@example.edu

      WEBWORK_TIMEZONE: America/Vancouver

      # disable prioritization of LTI1p3 jobs, this is performance tuning flag
      # as queries by priority was causing slowdowns with large amounts of jobs
      DELAYED_JOB_PRIORITIZE: 0

      # this is from us using MySQL as a Minion queue backend.
      # silence 'Mojo::mysql::PubSub is highly experimental' warning from Minion
      # https://github.com/preaction/Minion-Backend-mysql/issues/44
      MOJO_PUBSUB_EXPERIMENTAL: 1
      # show db migration errors with the Minion MySQL backend
      MOJO_MIGRATIONS_DEBUG: 1
      # show Webwork debug
      DEBUG: 1

  r:
    image: ubcctlt/rserve
    # The R server need not be available from outside the local Docker network.
    #ports:
    #  - "6311:6311"

  worker_lti1p3:
    <<: *app
    command: ./lib/DelayedJob/Run/run_all_jobs.pl
    ports: [] # override app's port settings to avoid port conflict

  # Mojolicious' Minion worker
  worker_mojo:
    <<: *app
    command: sudo -E -u www-data bin/webwork2 minion worker -m production
    ports: [] # override app's port settings to avoid port conflict

  # dev mail server for testing the mail system
  maildev:
    image: maildev/maildev
    ports:
      - '8071:1080'

volumes:
  oplVolume:
  mysql:
  webworkHtdocsData:
